name: Push-to-EC2

on:
  push:
    branches:
      - server

jobs:
  deploy:
    name: Deploy to EC2 on server branch push
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃 및 작업 디렉토리 설정
      - name: Checkout the files
        uses: actions/checkout@v3   # v3 버전으로 업그레이드
        with:
          path: Front  # 작업 디렉토리 설정

      # 2. SSH 설정
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key_Amazon 
          chmod 600 ~/.ssh/deploy_key_Amazon
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      # 3. 캐시 클리어 후 빌드 작업
      - name: Clean npm cache and Build project
        run: |
          cd Front
          npm cache clean --force
          npm install
          npm run build

      # 4. 서버 배포 - 배포 작업은 `ssh-deploy`로
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}  # 호스트 이름 또는 IP 주소
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # 5. 서버 재시작을 위한 SSH 명령 실행
      - name: Restart server and apply new build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}  # 호스트 이름 또는 IP 주소
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }} # SSH 키 사용
          
          script: |
            cd Front
            forever stopall || true  # 실행 중인 서버가 없을 경우에도 오류 무시
            sudo systemctl stop nginx
            git pull origin server
            npm install
            npm run build
            forever start -c "node server.js" .
            sudo systemctl restart nginx
