name: Push-to-EC2

on:
  push:
    branches:
      - server

jobs:
  deploy:
    name: Deploy to EC2 on server branch push
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃 및 작업 디렉토리 설정
      - name: Checkout the files
        uses: actions/checkout@v3
        with:
          path: Front

      # 2. SSH 설정
      - name: Set up SSH
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${EC2_SSH_KEY}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      # 3. 캐시 클리어 후 빌드 작업
      - name: Clean npm cache and Build project
        run: |
          cd Front
          npm cache clean --force
          npm install
          CI=false npm run build  # CI 환경을 false로 설정하여 경고를 무시

      # 4. 서버에 빌드 파일 배포
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # 5. 서버 상태 확인 및 문제 해결
      - name: Check Server Status and Restart if Needed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Node.js 서버 상태 확인
            echo "Checking Node.js process status..."
            forever list

            # 서버가 실행 중이지 않으면 다시 시작
            if ! forever list | grep -q "RUNNING"; then
              echo "Node.js server is not running. Starting server..."
              cd ${{ secrets.TARGET_DIR }}
              forever start server.js
            fi

            # Nginx 에러 로그 출력 (최근 20줄)
            echo "Checking Nginx error log..."
            sudo tail -n 20 /var/log/nginx/error.log

            # Nginx 캐시 삭제 및 재시작
            echo "Clearing Nginx cache and restarting Nginx..."
            sudo rm -rf /var/cache/nginx/*
            sudo systemctl restart nginx

      # 6. Nginx 및 Node.js 재시작 최종 확인
      - name: Final Check and Logs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Final verification of Node.js and Nginx..."
            forever list
            sudo tail -n 20 /var/log/nginx/error.log
